library(parallel)
library(devtools)

devtools::install_github("andrelmartins/bigWig", subdir="bigWig")

source("https://raw.githubusercontent.com/guertinlab/seqOutBias/master/docs/R/seqOutBias_hcsearch.R")

run.cutmask <- function(cutmask, seqoutbias.args, prefix = "run_", bw.split = FALSE, cleanup = TRUE, sqcmd = "seqOutBias") {

    outfilename = paste(prefix, cutmask, ".tbl", sep='')
    out_arg = paste("--out=", outfilename, sep='')
    bwfilename = paste(prefix, cutmask, ".bw", sep='')
    bw_arg = paste("--bw=", bwfilename, sep='')
    mask_arg = paste("--kmer-mask=", cutmask, sep='')
    cmd = paste(sqcmd, seqoutbias.args, mask_arg, "--skip-bed", out_arg, bw_arg)
    
    # execute
    print(cmd)
    system(cmd)
    
    
    # clean up - remove files specific to this execution
    if (cleanup) {
        cat("deleting stuff ....\n")
        cat("rm", outfilename,"\n")
        unlink(outfilename)
    }
    
    # return output file names
    if (bw.split) {
        c(paste(prefix, cutmask, "_plus.bw", sep=''), paste(prefix, cutmask, "_minus.bw", sep=''))
    } else {
        c(bwfilename, bwfilename)
    }
}


load.sites <- function(filenames) {
    lapply(filenames, function(filename) {
        fimo = read.table(filename, skip = 1, sep ='\t')
        len.vec.values = length(fimo[,7])
        if (length(fimo[,7]) > 3000000 ){
            subset.len = len.vec.values - 300000
            sort.sub = sort(fimo[,7], partial=subset.len)[subset.len]
            top.index = which(fimo[,7] > sort.sub)
            fimo.small = fimo[top.index,]
            bed6 = fimo.small[, c(3,4,5,2,7,6)]
        } else {
             bed6 = fimo[, c(3,4,5,2,7,6)]
        }
        bed6
    }) 
}


hc.search.mods <- function(sites, start_mask, seqoutbias.args, prefix = "run_", 
                           bw.split = FALSE, cleanup = TRUE, sqcmd = "seqOutBias", mc.cores = 20) {
    neighbors <- function(vecmask) {
                                        # generate list of neighboring masks that differ
                                        # by the addition of a single unmasked position
        result <- vector(mode="list", length=length(vecmask))
        n <- 0
        for (k in 1:length(vecmask)) {
            if (vecmask[k] == -1) { # X
                n <- n + 1
                vi = vecmask
                vi[k] = 1 # N
                result[[n]] <- vec.to.mask(vi)
            }
        }
        
        if (n == 0) return(NULL)
        result[1:n]
    }                                 #
    mask = character()
    score = numeric()
    rtable = data.frame(c(score, mask), stringsAsFactors=FALSE)
    nextlst = neighbors(mask.to.vec(start_mask))
    
        while (!is.null(nextlst)) {
            print(nextlst)
            scores = mclapply(nextlst, function(cutmask) {
                if (file.exists(paste0('runhc_mo9_', cutmask, '.bw'))) {
                    bw.plus = load.bigWig(paste0('runhc_mo9_', cutmask, '.bw'))    
                    bw.minus = load.bigWig(paste0('runhc_mo9_', cutmask, '.bw'))
                } else {
                    bw.paths = run.cutmask(cutmask, seqoutbias.args, sqcmd=sqcmd, prefix=prefix)
                    bw.plus = load.bigWig(bw.paths[1])
                    bw.minus = load.bigWig(bw.paths[2])
                }
                    score = eval.cutmask(sites, bw.plus, bw.minus)
                    data.frame(score = score, mask = cutmask, stringsAsFactors=FALSE)
            }, mc.cores = mc.cores)
            scores.values = sapply(scores, function(pair) pair$score)
            
                                        # pick the neighbor with the best score
            k = which.min(scores.values)[1]
            mask = scores[[k]]$mask
            cat(scores.values[k], mask, "\n")
            rtable = rbind(rtable, scores[[k]])
            print(rtable)
                                        # next
            nextlst <- neighbors(mask.to.vec(mask))
        }
    rtable
}
   


system('mkdir C1_gDNA_rep1')
setwd('C1_gDNA_rep1')


seqOutBias.args = "../hg38.fa ../C1_gDNA_rep1.bam --plus-offset=10 --minus-offset=10 --read-size=30"

seqOutBias.cmd = "seqOutBias"


initial.mask = "XXXXXXXXXXXXXXXXXXXXX"


sites = load.sites(c("../rep1_ATAC_bias_pe1_minus_00005_fimo.txt", "../rep1_ATAC_bias_pe1_plus_00005_fimo.txt", 
                     "../rep1_ATAC_bias_pe2_minus_00005_fimo.txt", "../rep1_ATAC_bias_pe2_plus_00005_fimo.txt"))

#I run the next line in the directory to get the tallymer file (takes a long time, but only once per directory)
#otherwise running this in parallel gets messed up if the tallymer file is being generated by multiple calls
#alternatively one can specify a talymer file location in the argument or just move the tallymer files
system(paste('seqOutBias ', seqOutBias.args, 
   ' --no-scale --out=runhc_21merrep1_XXXXXXXXXXXXXXXXXXXXX.tbl --bw=runhc_21merrep1_XXXXXXXXXXXXXXXXXXXXX.bw'))

result.table = hc.search.mods(sites, initial.mask, 
                seqOutBias.args, prefix = "runhc_21merrep1_", sqcmd = seqOutBias.cmd, mc.cores = 20)
#use more mc.cores if you have more than 20 X in the mask
